---
version: "2"

run:
  timeout: 5m
  go: "1.21"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
