---
run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
